title: top 10nuffies of al time
author: XxNuggieMasterxX
email: nuggieman@nuggie.com
description: > # this means to ignore newlines until "baseurl:"
  Hey listenup sheepleaw me the nuggie mansteter isd ghgonaabe talkging about
  the berset nuggies of lallt tiem imama talk  about mcddons nuggies weeddty
  nuggeis imma ecen talk about mmoma nufgies starp in nuggos sthis gonanabe awild ride

# social links
twitter_username: @Nuggos
github_username:  NuggoMan

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
